### ISSUE TITLE
Invisible sidewalk in BOABO? 

### ISSUE THREAD

**Issue by JRC1999** [GTAmodding/GTAIV-Issues-List#101]
I can't seem to figure this out. I'm on 1.0.8.0.

The mods I have are as follows: FusionFix (the Pre-CE version by Zolika), Various Fixes, ZolikaPatch, Character Fixes, Jim Fitzgerald fix (separate from the Character Fixes mod), HQ Vehicle Pack by Ash, radio downgrade, and a couple of clothing mods. Oh, and DXVK.  I've reverted Various Fixes and that hasn't worked. 
I'm partially wondering if anyone's seen this, and partially wondering how to fix it. I can't imagine any of the mods except VariousFixes would have any effect on it, since none of the others effect the map.
![20230906013111_1](https://github.com/GTAmodding/GTAIV-Issues-List/assets/144276937/ba386cb9-205b-40e0-b928-7148fa91dea0)
![20230907215054_1](https://github.com/GTAmodding/GTAIV-Issues-List/assets/144276937/9e76da6d-69c5-4861-9333-63170f9bb63e)
![20230907215057_1](https://github.com/GTAmodding/GTAIV-Issues-List/assets/144276937/d2a4914b-e4c0-4836-ad3b-d8258c9f9dfe)

**Comment by JRC1999** [comment]
UPDATE: I have completely started from scratch- now on CE, no mods, nothing. Still invisible.

**Comment by r3538987** [comment]
1070
https://i.imgur.com/0VgsGMR.jpeg

**Comment by JRC1999** [comment]
> 1070 https://i.imgur.com/0VgsGMR.jpeg

Will give that a try and report back.

**Comment by JRC1999** [comment]
> 1070 https://i.imgur.com/0VgsGMR.jpeg
Didn't work. Issue still persists. This is weird. GPU Driver is up to date.

**Comment by JRC1999** [comment]
I'm still not sure _what_ triggers it, but deleting the Profiles folder in My Documents/Rockstar Games/GTAIV fixed it. Now I get to start fresh and reinstall all my mods because everything got jumbled up while I tried to track it down lol

**Comment by r3538987** [comment]
Issues in environment most likely happen when save file version mismatches. At least it was on my end like that. 
Save file made on version X, and you a playing version Y. 

Game still will load file, but minor problems can show up.
