### ISSUE TITLE
A nice and important change

### ISSUE THREAD

**Issue by Dr1Ft3RXII** [GTAmodding/GTAIV-Issues-List#102]
I would like to ask you to add an option to choose between PC and console trees, the same when it comes to reflections and changing the language in the menu as in previous titles, along with languages ​​that have not been officially added but were made by the community

**Comment by r3538987** [comment]
Trees - why not use Console Visuals mod, implementing dynamic thing is quite complicated.
Reflections - same.
Language - do you really need that often switch language? Only can image this sort of useful you do some kind of translation.
