### ISSUE TITLE
TBoGT Cutscene glitch (popping or something)

### ISSUE THREAD

**Issue by Lethality5001** [GTAmodding/GTAIV-Issues-List#104]
During cutscenes sometimes in Tbogt u see some weird kind of glitching, not sure exactly how to describe it but i will post a video of it
Its like some sort of flickering but not exactly, will show vid here

Most obvious at 0:45 but happens throughout the video too
Its happening even at first Tony mission too

(Patch 1.0.7.0) Happens on 1.0.8.0 and CE too (Fusionfix, console visuals, variousfixes already installed)

https://github.com/GTAmodding/GTAIV-Issues-List/assets/145836476/c65bfb0a-5d0f-4574-8066-1cee71f9e461

**Comment by Tomasak** [comment]
this is for vanilla issues only list

**Comment by Lethality5001** [comment]
> this is for vanilla issues only list

and this is an issue...
