### ISSUE TITLE
Where are all the other options ?

### ISSUE THREAD

**Issue by Dodo93150** [GTAmodding/GTAIV-Issues-List#106]
![GTAIV EFLC FusionFix – Bloc-notes 26_09_2023 17_51_22](https://github.com/GTAmodding/GTAIV-Issues-List/assets/146113808/cb0aadc6-b24f-4812-b50b-eb359415cdae)
I downloaded FusionFix via ItsClonkAndre's DOwngrader but all the options shown on GTAforums aren't here

**Comment by Tomasak** [comment]
only ff from official link https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix is supported
not to mention this is issue list for vanilla game bugs

**Comment by Dodo93150** [comment]
I didn't fully understand what you said, can you please explain again, also
how do I download and use the Mod ?

**Comment by Tomasak** [comment]
download [GTAIV.EFLC.FusionFix.zip](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/releases/download/v1.96/GTAIV.EFLC.FusionFix.zip)
CE support only for now (next update should be backwards compatible)

**Comment by Dodo93150** [comment]
It means I can't use it with patch 1.0.7.0 ?
