### ISSUE TITLE
Traffic lights are displayed incorrectly

### ISSUE THREAD

**Issue by Adamantium86** [GTAmodding/GTAIV-Issues-List#107]
![image](https://github.com/GTAmodding/GTAIV-Issues-List/assets/145924820/61415ea2-f28d-4ffd-a825-a88a9c6dd81d)
![image](https://github.com/GTAmodding/GTAIV-Issues-List/assets/145924820/2b841b5a-9356-44b3-bdc2-8f29cc932e0c)

**Comment by r3538987** [comment]
Possible to provide more info about your setup (game version/used mods), because currently we are in fortune telling on the cards, as these screens doesn't give much information.
I cannot remember such problem on my side.

Based on shadow quality, it's more likely you have Complete Edition game.

**Comment by Adamantium86** [comment]
Game version - latest steam complete edition.No mods latest accept Fusion Fix.My setup is:I7 4930K, 16 Gb ram, gtx980ti, windows 10.Отправлено с iPhone26 сент. 2023 г., в 22:59, r3538987 ***@***.***> написал(а):﻿
Possible to provide more info about your setup (game version/used mods), because currently we are in fortune telling on the cards, as these screens doesn't give much information.
I cannot remember such problem on my side.

**Comment by Adamantium86** [comment]
Solved by replacing shader "gta_emissivestrong.fxc" in
folder GTAIV\common\shaders\win32_30_nv8 from this
https://github.com/robi29/GTA-IV-Shaders


ср, 27 сент. 2023 г. в 12:44, 8AdamantiuM8 ***@***.***>:

**Comment by RecklessGlue540** [comment]
This issue happens because of the Z-fighting Fix.
Update FusionFix, or use these traffic light models which use the correct shaders: https://github.com/Parallellines0451/GTAIV.EFLC.FusionShaders/tree/main/other_assets/Fixed%20Traffic%20Lights/traffic.img

This issue can be closed.
