### ISSUE TITLE
game crashes when you try and load a save game or start a new game

### ISSUE THREAD

**Issue by williamg209** [GTAmodding/GTAIV-Issues-List#109]
ive got the worst bug possible that it crashes when i try and start a save or load a save, making the game dead

**Comment by r3538987** [comment]
You run some mods? What's game version?

**Comment by williamg209** [comment]
i installed lcpdfr and it worked for a bit then the issue started, ive removed it and uninstalled the game multiple times, now the only mods i have are these and it still crashes
________________________________

**Comment by r3538987** [comment]
If you saved game with mods in place this usually leaves traces in file, and this can affect game if mods are changed or removed as in your case.

Plus this repository is for vanilla game issues only. So this report not exactly fits here. =/

**Comment by williamg209** [comment]
It is a vanilla game I said the only mods I have technically is this,
________________________________

**Comment by Tomasak** [comment]
This page is for reporting vanilla bugs only.
If you have mods installed its that leave extra files, you have to remove those too.
