### ISSUE TITLE
Police lightbar missing visual effect 

### ISSUE THREAD

**Issue by DryChicken47** [GTAmodding/GTAIV-Issues-List#111]
The glowing effect on the environment works, but the lightbar itself misses the effect in my game.

![image](https://github.com/GTAmodding/GTAIV-Issues-List/assets/97366226/3efbf029-f353-4a8a-b82e-ba891a1feda8)

![image](https://github.com/GTAmodding/GTAIV-Issues-List/assets/97366226/9dcddca6-e7ea-49c2-a15d-392f66360054)

**Comment by valentyn-l** [comment]
> The glowing effect on the environment works, but the lightbar itself misses the effect in my game.
> 
> ![image](https://user-images.githubusercontent.com/97366226/275338975-3efbf029-f353-4a8a-b82e-ba891a1feda8.png)
> 
> ![image](https://user-images.githubusercontent.com/97366226/275338997-9dcddca6-e7ea-49c2-a15d-392f66360054.png)

This is a known issue with Console Shadows ON and is currently being looked into.

You can turn Console Shadows OFF for now and the effect will be activated.

**Comment by Tomasak** [comment]
> > The glowing effect on the environment works, but the lightbar itself misses the effect in my game.
> 
> This is a known issue with Console Shadows ON and is currently being looked into.
> 
> You can turn Console Shadows OFF for now and the effect will be activated.
Thus not a vanilla game issue.
