### ISSUE TITLE
Latest version of the Fusion Fix (v2.00) causes a Social Club error that blocks you from saving the game!

### ISSUE THREAD

**Issue by Ozgunos** [GTAmodding/GTAIV-Issues-List#115]

**Comment by r3538987** [comment]
https://github.com/GTAmodding/GTAIV-Issues-List/issues?q=is%3Aissue+is%3Aclosed#issuecomment-1735306452
@Tomasak Can we rename this repository to: GTAIV--VANILLA--Issues-List ?

**Comment by Ozgunos** [comment]
The Complete Edition 1.2.0.43

**Comment by Ozgunos** [comment]
Sorry wrong issue page

**Comment by RecklessGlue540** [comment]
This list is not for FusionFix introduced issues. This can be closed.
Either way, make sure you're using the latest version of the game 1.2.0.59 from either RGL or Steam...
FusionFix does not change anything related to Social Club in any way either...
