### ISSUE TITLE
Inconsistent menu options between title screen and in-game pause menu

### ISSUE THREAD

**Issue by SandeMC** [GTAmodding/GTAIV-Issues-List#123]
For some reasons, the menu options are inconsistent between the title screen and in-game pause menu. Differences I found:
## Controls
- [The controller texture in the controller settings is missing in main menu while it is OK in pause menu](https://github.com/GTAmodding/GTAIV-Issues-List/issues/103)
## Display
- Missing `Brightness`, `Contrast`, `Saturation` options on title. Could also throw in an example image to actually have some assist tweaking it? Maybe an empty gap to show the title art?
## Game
- Missing `Load`, `New`, `Autosave`, making it impossible to load or start a new game from the title menu if you have an existing savefile.
- Also missing `Social Club` and `QUIT`, but those are available on the title screen itself, so it's not a big issue.
## Other
- Missing spacing between the last options in places that have one. Seems to be inconsistent (Display, Controls menus is where I had that happening; sometimes in-game, sometimes on title.)

**Comment by Tomasak** [comment]
1) works fine
2) design choice, you can see differnece only in game
3) design choice
4) bug, space randomly appears.
