### ISSUE TITLE
[BUG] I have two problems with the rain

### ISSUE THREAD

**Issue by Otheucarvalho** [GTAmodding/GTAIV-Issues-List#126]
First problem: the rain drops don't have that impact effect when they collide with the ground, cars, player or any surface and this looks strange because the rain is working almost perfectly but this detail makes it look strange.

Second problem: when I'm under some cover, the rain passes through it, even in safe houses, apartments and interiors.

I'm using the Steam version of the game and the latest fusionfix update and I've always fixed this bug.

Sorry my English

![Bug Rain Cover](https://github.com/GTAmodding/GTAIV-Issues-List/assets/153325418/ffc96154-da85-4528-8508-39ec9a567854)
![Bug Rain Cover2](https://github.com/GTAmodding/GTAIV-Issues-List/assets/153325418/ec0c24f6-8e93-44df-9d61-b7cd471590b9)
![Bug Rain](https://github.com/GTAmodding/GTAIV-Issues-List/assets/153325418/7fe69650-1840-42ab-9ac5-a08c3a2191fe)

**Comment by Tomasak** [comment]
Do you have scripthook dotnet installed?

**Comment by Otheucarvalho** [comment]
> Você tem o scripthook dotnet instalado?



> Do you have scripthook dotnet installed?

Yes, do
![image](https://github.com/GTAmodding/GTAIV-Issues-List/assets/153325418/85303ccd-c167-45ef-a92e-028f8432eeaa)

**Comment by Tomasak** [comment]
issue is caused by that. not a vanilla issue.

**Comment by r3538987** [comment]
FusionFix had an report template created, I'm thinking such thing would be useful here as well.

**Comment by Otheucarvalho** [comment]
I understand, I will solve this problem there too, thank you for your attention.
