### ISSUE TITLE
Duplicate properties in GTAIV.EFLC.FusionFix.cfg

### ISSUE THREAD

**Issue by kevinveiga** [GTAmodding/GTAIV-Issues-List#127]
several properties are duplicated in the GTAIV.EFLC.FusionFix.cfg file after changing in-game

**Comment by SandeMC** [comment]
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issue is for FusionFix issues. This is for GTA IV Vanilla issues.

**Comment by Tomasak** [comment]
as said.
try removing the cfg and not manually editing it.
if issue persists, create an issue in fusionfix repo

**Comment by kevinveiga** [comment]
> as said. try removing the cfg and not manually editing it. if issue persists, create an issue in fusionfix repo

thanks man, this worked!!!
