### ISSUE TITLE
Just a little question about Fusion Fix ini configuration

### ISSUE THREAD

**Issue by JesperUlquiorra** [GTAmodding/GTAIV-Issues-List#129]
Hello there!

First of all, I would like to thank the whole team behind Fusion Fix and many other mods, you're amazing people!

I've been trying and setting some options in the ini file (fixing the taxi bug, for example), and I was wondering if I could use some of your help since I would like to try different RecoilFix options in the [MAIN] section. It seems to me that the recoil effect should be off (like it is in the vanilla version with no mods from the Steam GTA IV CE installation) with a "cero" value in the fix ini. Are there other options too?

I have other questions about different topics, so if someone would like to share some knowledge about them, I would seriously appreciate it.

I know it is a simple detail, but having my second playthrough got me with this curiosity about exploring these options and more.

Thanks again! Hope you can help me.^^

EDIT: Does anyone know how to reactivate the volumetric light/shadows after applying the DXVK mod to a fusion fix modded GTA IV?

**Comment by SandeMC** [comment]
This isn't FusionFix's repository.
