### ISSUE TITLE
Not sure if it's because of this mod, real recoil mod fix

### ISSUE THREAD

**Issue by bardan1** [GTAmodding/GTAIV-Issues-List#134]
so i really like this mod paired with realistic weapon stats 
https://www.gtagaming.com/real-recoil-f30353.html
it kind of works but the camera acts weirdly and recoil is not felt as it should.
Is it because of any mouse fixes in this mod ??
and if it is how can i disable. I remember there being a Mouse fix parameter in  older version FusionFix.ini

**Comment by SandeMC** [comment]
"in this mod" this isn't even FusionFix's repository.

**Comment by bardan1** [comment]
> "in this mod" this isn't even FusionFix's repository.

well it works without the mod fine

**Comment by Tomasak** [comment]
This list is for vanilla game issues only.
But with your problem:
disable RecoilFix = 1 by changing to 0
aka RecoilFix = 0 in fusionfix.ini
if issue persists open issue in FusionFix repo
