### ISSUE TITLE
Distance Blur and Depth of Field settings in Display tab don't do anything

### ISSUE THREAD

**Issue by Echo-Phyber** [GTAmodding/GTAIV-Issues-List#138]
It did work but stopped all of a sudden. I'm on the latest version. Tried reinstalling older versions, nothing helps.

**Comment by r3538987** [comment]
This is vanilla game issue list.
Such settings, are from FusionFix, probably you should try report it here. 
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix
