### ISSUE TITLE
Raining effect still can be seen when you're under something and even when you're inside the interior

### ISSUE THREAD

**Issue by idontdomuch** [GTAmodding/GTAIV-Issues-List#148]
https://files.catbox.moe/v4o2nx.mp4

Rain effect is still on screen when your character is inside building. It doesn't make raindrop sound but you still can see rain effect on your screen. 
This happened on both GTA4 and EFLC

**Comment by idontdomuch** [comment]
My setting
![setting1](https://github.com/GTAmodding/GTAIV-Issues-List/assets/167036819/ee66292f-213c-4ac0-a968-170a1ae616b8)
![setting2](https://github.com/GTAmodding/GTAIV-Issues-List/assets/167036819/7274d3b8-eafd-4a3d-ba3f-aca98d5aacfa)

**Comment by idontdomuch** [comment]
![image](https://github.com/GTAmodding/GTAIV-Issues-List/assets/167036819/d94e0525-200f-452a-8d6d-ba6396d65055)
even when you're under bridge or anything that's supposed to blocks rain

**Comment by Tomasak** [comment]
scripthook dotnet bug
