### ISSUE TITLE
CRASHES AFTER 5MIN OR HIGH SPEEDS WITH CAR ALSO MISSION BROKEN.

### ISSUE THREAD

**Issue by Stupter1** [GTAmodding/GTAIV-Issues-List#155]
The one Vlad mission with the Car wash is broken, cant use CAR WASH,
secondly, I have GTA 4 1.0.7.0 , Fusion fix crashes after doing random things or going high speeds in cars
I use DXVK and Fusionfix only. 
its so annoying cuz i want extra definition, anti aliasing, motion blur,
Maybe make a seperate mod with these graphic options, or fix fusionfix idk, i would love using your mod,

Please fix asap PLS i tried everything even modifiyng your mod but nothing worked...

**Comment by Tomasak** [comment]
This is for vanilla issues, not fusion fix bugs
