### ISSUE TITLE
TLaD clubhouse crash when memorial wall is full

### ISSUE THREAD

**Issue by Javiolini** [GTAmodding/GTAIV-Issues-List#159]
When the memorial wall in The Lost clubhouse becomes full of plaques, the game will crash when it attempts to load it. The max amount of plaques it allows is 24 from my own testing but it may allow up to 28 from what I've read. The loading occurs at the base of the stairs to the second floor, and it extends a little beyond the wall so that it makes it impossible to get into the innovation bike parked outside, as doing so will trigger the load and crash the game.
The second floor can still be accessed via the roof, doing so will show the wall in the default state with only the Lil' Joe plaque.

This bug is present in all versions of the game as far as i know, as i've found discussions of it happening on console back in 2010.

**Comment by Tomasak** [comment]
already reported in #37
