### ISSUE TITLE
Compatibility with Intel Iris Xe Integrated GPU

### ISSUE THREAD

**Issue by Haisom** [GTAmodding/GTAIV-Issues-List#179]
I'm not sure if it's for me only but I get these black square artifacts in some shaders. I get this in some effects like Niko's face, some NPC hairs/beards, and some objects around the city like trees and other stuff are just plain black. Tried using Fusion Fix and Various Fixes but it's still the same.

I have also tried GTA IV Setup Utility for DXVK but the results are the same.

My Hardware:

OS: Microsoft Windows 11 Home Single Language (10.0, Build 22631)
CPU: 12th Gen Intel(R) Core(TM) i5-1235U 10/12
RAM: 8 GB
STORAGE: SAMSUNG MZVLQ256HBJD-00B (238,5 GB/Fixed hard disk media)
GPU: Intel(R) Iris(R) Xe Graphics (1 GB)

![image](https://github.com/user-attachments/assets/3b42a57b-d142-47de-9494-e230a650bae1)

![image](https://github.com/user-attachments/assets/6c2dbccc-f0d3-4e45-a3ae-d675b907d8e3)

![image](https://github.com/user-attachments/assets/0cabaf85-3f84-4a40-95ab-3eecb1b9bf6b)

**Comment by ThirteenAG** [comment]
That happens with d3d9on12, possibly a driver/translation layer bug.

**Comment by Haisom** [comment]
I see... Any possible workaround?

**Comment by Haisom** [comment]
Could this help? https://github.com/narzoul/ForceD3D9On12

**Comment by Haisom** [comment]
I think I might have solved the issue but still didn't have time to reinstall the game. Seems my "manufacturer driver" wasn't so updated as they were telling me, it was like 10 versions behind the official intel release. So it was probably just the video driver.
