### ISSUE TITLE
Incorrect LOD in Ferris Wheel on Firefly Island

### ISSUE THREAD

**Issue by NazarSurmay12** [GTAmodding/GTAIV-Issues-List#192]
![GTAIV_2024_12_24_14_09_33_232](https://github.com/user-attachments/assets/8b3364c8-308b-4ff6-9397-e3f605eac6d9)
![GTAIV_2024_12_24_14_09_35_927](https://github.com/user-attachments/assets/59733782-6a8d-4fa3-9b04-18758a1f2749)

**Comment by Tomasak** [comment]
Corrupted save file
