### ISSUE TITLE
Phone doesn't work

### ISSUE THREAD

**Issue by kolby4587** [GTAmodding/GTAIV-Issues-List#61]
when ever someone calls me and i accept instead of actually accepting it he will put the phone away. if i use my arrow keys to move the keypad on the phone it will still make noise. this happens for me on controller and keyboard

**Comment by manuelperarnau** [comment]
I am having the same issue one TBOGT. The call is accepted without dialogue. Thank you

**Comment by manuelperarnau** [comment]
> I am having the same issue one TBOGT. The call is accepted without dialogue. Thank you

Hey I should have mentioned that I am running several mods including Simple Native Trainer. I first started by removing the both the ini and asi "Trainertbogt" without success. Later I found a post that if you disable the "Phone sleep mode" it might solve the issue and it did! I do it now every time I resume the game.

Hope it helps

**Comment by ThirteenAG** [comment]
This is a list of bugs in latest version of the game, without any mods.
