### ISSUE TITLE
1.2.0.43 has downgraded save load mechanism

### ISSUE THREAD

**Issue by valsorai** [GTAmodding/GTAIV-Issues-List#66]
From my experience, when you launch the game it **only loads the most recent manual save of each episode and doesn't load the most recent autosaves** like the previous versions (1.0.7.0 for example) did.
So when I exit the game, relying on autosave, when I'll launch it up again I'll have to remember to load my autosave because game loads me into the manual save.

**Additionaly, time stamps on saves are kind of broken**, as they indicate the same date for the manual save and its respective autosave, despite the fact that they might have a different date.So when you try to figure out which of your saves is the most recent, this issue gets in the way as well. This bug might be the consequence of poorly implemented cloud saves in the post march 19th 2020 versions, I don't know!

So I think these are two pretty annoying issues because they create more inconvenience in comparison to playing on older versions of the game. I prefer to use 1.2.0.43 for singleplayer so I would be glad to see these 2 issues fixed as part of fusion fix if possible, thanks!

**Comment by Tomasak** [comment]
I think this is not a game bug, but actually Rockstar Games launcher bug. Try playing without cloud support if timestamps are broken too.

**Comment by valsorai** [comment]
> I think this is not a game bug, but actually Rockstar Games launcher bug. Try playing without cloud support if timestamps are broken too.

Ok I'll try to play without cloud saves and I'll update the ticket

**Comment by valsorai** [comment]
Turning off cloud saves fixed both issues! Thank you for help Tomasak
