### ISSUE TITLE
texture bug around the 2nd appartement of Niko

### ISSUE THREAD

**Issue by Hug0Ghost** [GTAmodding/GTAIV-Issues-List#87]
![20220811134310_1](https://user-images.githubusercontent.com/111059266/184127498-4a02ecc9-0d7e-48c2-ba5a-a44306a047b2.jpg)
I already had that on 1.0.8.0

**Comment by Hug0Ghost** [comment]
The commandline -scOfflineOnly fixed it

**Comment by Tomasak** [comment]
Save corruption caused by map editing or colaccel cache bug - delete its dat files
