### ISSUE TITLE
The carheadlights cannot reflect the Niko's shadow

### ISSUE THREAD

**Issue by b9348** [GTAmodding/GTAIV-Issues-List#91]
![1](https://user-images.githubusercontent.com/41979647/225900007-88c3f30c-e9e6-4987-a22b-c6cc0614c5de.png)
![2](https://user-images.githubusercontent.com/41979647/225900024-230279a4-bd3a-489f-8669-69bd38f25c45.png)

**Comment by b9348** [comment]
common\shaders\win32_30_nv8
deferred_lighting.fxc

**Comment by Tomasak** [comment]
This is caused by fusion fix's night shadow flicker fix

**Comment by SemiLoanBike** [comment]
I'm unable to turn off the FlickeringShadowsFix in fusionfix. I tried changing the value to 0 in the .ini file but it does nothing. Any tips? Atm headlights don't cast any shadows for me even with night shadows enabled

**Comment by SerGhost1915** [comment]
How can I resolve that. I have the same problem
