### ISSUE TITLE
EFLC missing From GtaIV complete edition

### ISSUE THREAD

**Issue by Rafeal363** [GTAmodding/GTAIV-Issues-List#93]
i have Downgrade the game to 1.0.7.0 
As the title says. When i boot up the game there is no option to select any of the DLC TLAD or TBOGT, only the regular GTAIV 
Any solution for this? I had downgraded by tool GTAIVDowngrader v1.9
and its work Fine Except DLC is missing 
so Ineed fix for it
I have GTAIV complete edition steam version 

The Game start to this screen no DLC
![Screenshot_2](https://github.com/GTAmodding/GTAIV-Issues-List/assets/135209206/f2c00230-3b66-495b-816e-176b57fabd7f)

**Comment by ThirteenAG** [comment]
This repo is for clean game issues.

**Comment by Rafeal363** [comment]
I already Have A clean Game Version 
First get A clean Game 
2ed and last use GTAIVDowngrader v1.9
Then Finished  & this issue Appears to me how to fix it
