### ISSUE TITLE
FusionFix v1.89 Toggling extra options in menu toggles all of them (Example: Console shadows)

### ISSUE THREAD

**Issue by JRC1999** [GTAmodding/GTAIV-Issues-List#99]
Like the title says, every time I try to change any of the extra options, they all change except for motion blur
![20230906151653_1](https://github.com/GTAmodding/GTAIV-Issues-List/assets/144276937/e1dffa5d-f90e-4fdd-a49d-934672c4f27e)
![20230906151654_1](https://github.com/GTAmodding/GTAIV-Issues-List/assets/144276937/724417f7-9854-4464-8d94-0567ddfb1bd7)

Game is on 1.0.8.0 if that's relevant.

**Comment by r3538987** [comment]
I think this repository is for overall vanilla game, so I would say you issue will be more appropriate in FusionFix repo. 
As these additional options are introduced by that mod. 
Which versions you use I don't know, for CE or preCE (v1070/v1080).

**Comment by JRC1999** [comment]
> I think this repository is for overall vanilla game, so I would say you issue will be more appropriate in FusionFix repo. As these additional options are introduced by that mod. Which versions you use I don't know, for CE or preCE (v1070/v1080).

Aw man, I was brought here by the fusionfix thread on GTAForums lol. I'll post it over there. It's 1.0.8.0

**Comment by r3538987** [comment]
But with 1080 you must go to Zolika's fork version. As main repository dont support these old versions.
https://github.com/Zolika1351/GTAIV.EFLC.FusionFix

**Comment by JRC1999** [comment]
I see, thank you

**Comment by Legacy7K** [comment]
I also have this issue. I can only toggle all, not individual options
